/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context } from "./src/Api/context"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Json";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Json";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  CommentCreateInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutCommentsInput'] | null; // UserCreateOneWithoutCommentsInput
    contain: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    post: NexusGenInputs['PostCreateOneWithoutCommentsInput']; // PostCreateOneWithoutCommentsInput!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentCreateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutauthorInput'] | null> | null; // [CommentCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutAuthorInput'] | null> | null; // [CommentCreateWithoutAuthorInput]
  }
  CommentCreateManyWithoutPostInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutpostInput'] | null> | null; // [CommentCreateOrConnectWithoutpostInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutPostInput'] | null> | null; // [CommentCreateWithoutPostInput]
  }
  CommentCreateOrConnectWithoutauthorInput: { // input type
    create: NexusGenInputs['CommentUncheckedCreateWithoutAuthorInput']; // CommentUncheckedCreateWithoutAuthorInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateOrConnectWithoutpostInput: { // input type
    create: NexusGenInputs['CommentUncheckedCreateWithoutPostInput']; // CommentUncheckedCreateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateWithoutAuthorInput: { // input type
    contain: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    post: NexusGenInputs['PostCreateOneWithoutCommentsInput']; // PostCreateOneWithoutCommentsInput!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentCreateWithoutPostInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutCommentsInput'] | null; // UserCreateOneWithoutCommentsInput
    contain: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentListRelationFilter: { // input type
    every?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    none?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    some?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
  }
  CommentOrderByInput: { // input type
    authorId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    contain?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    postId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CommentScalarWhereInput: { // input type
    AND?: Array<NexusGenInputs['CommentScalarWhereInput'] | null> | null; // [CommentScalarWhereInput]
    authorId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    contain?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: Array<NexusGenInputs['CommentScalarWhereInput'] | null> | null; // [CommentScalarWhereInput]
    OR?: Array<NexusGenInputs['CommentScalarWhereInput'] | null> | null; // [CommentScalarWhereInput]
    postId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  CommentUncheckedCreateInput: { // input type
    authorId?: number | null; // Int
    contain: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    postId: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentUncheckedCreateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutauthorInput'] | null> | null; // [CommentCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutAuthorInput'] | null> | null; // [CommentCreateWithoutAuthorInput]
  }
  CommentUncheckedCreateManyWithoutPostInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutpostInput'] | null> | null; // [CommentCreateOrConnectWithoutpostInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutPostInput'] | null> | null; // [CommentCreateWithoutPostInput]
  }
  CommentUncheckedCreateWithoutAuthorInput: { // input type
    contain: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    postId: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentUncheckedCreateWithoutPostInput: { // input type
    authorId?: number | null; // Int
    contain: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentUncheckedUpdateInput: { // input type
    authorId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    postId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUncheckedUpdateManyInput: { // input type
    authorId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    postId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUncheckedUpdateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutauthorInput'] | null> | null; // [CommentCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutAuthorInput'] | null> | null; // [CommentCreateWithoutAuthorInput]
    delete?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['CommentScalarWhereInput'] | null> | null; // [CommentScalarWhereInput]
    disconnect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    set?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    update?: Array<NexusGenInputs['CommentUpdateWithWhereUniqueWithoutAuthorInput'] | null> | null; // [CommentUpdateWithWhereUniqueWithoutAuthorInput]
    updateMany?: Array<NexusGenInputs['CommentUpdateManyWithWhereWithoutAuthorInput'] | null> | null; // [CommentUpdateManyWithWhereWithoutAuthorInput]
    upsert?: Array<NexusGenInputs['CommentUpsertWithWhereUniqueWithoutAuthorInput'] | null> | null; // [CommentUpsertWithWhereUniqueWithoutAuthorInput]
  }
  CommentUncheckedUpdateManyWithoutCommentsInput: { // input type
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    postId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUncheckedUpdateManyWithoutPostInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutpostInput'] | null> | null; // [CommentCreateOrConnectWithoutpostInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutPostInput'] | null> | null; // [CommentCreateWithoutPostInput]
    delete?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['CommentScalarWhereInput'] | null> | null; // [CommentScalarWhereInput]
    disconnect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    set?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    update?: Array<NexusGenInputs['CommentUpdateWithWhereUniqueWithoutPostInput'] | null> | null; // [CommentUpdateWithWhereUniqueWithoutPostInput]
    updateMany?: Array<NexusGenInputs['CommentUpdateManyWithWhereWithoutPostInput'] | null> | null; // [CommentUpdateManyWithWhereWithoutPostInput]
    upsert?: Array<NexusGenInputs['CommentUpsertWithWhereUniqueWithoutPostInput'] | null> | null; // [CommentUpsertWithWhereUniqueWithoutPostInput]
  }
  CommentUncheckedUpdateWithoutAuthorInput: { // input type
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    postId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUncheckedUpdateWithoutPostInput: { // input type
    authorId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUpdateInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutCommentsInput'] | null; // UserUpdateOneWithoutCommentsInput
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    post?: NexusGenInputs['PostUpdateOneRequiredWithoutCommentsInput'] | null; // PostUpdateOneRequiredWithoutCommentsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUpdateManyMutationInput: { // input type
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUpdateManyWithWhereWithoutAuthorInput: { // input type
    data: NexusGenInputs['CommentUncheckedUpdateManyWithoutCommentsInput']; // CommentUncheckedUpdateManyWithoutCommentsInput!
    where: NexusGenInputs['CommentScalarWhereInput']; // CommentScalarWhereInput!
  }
  CommentUpdateManyWithWhereWithoutPostInput: { // input type
    data: NexusGenInputs['CommentUncheckedUpdateManyWithoutCommentsInput']; // CommentUncheckedUpdateManyWithoutCommentsInput!
    where: NexusGenInputs['CommentScalarWhereInput']; // CommentScalarWhereInput!
  }
  CommentUpdateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutauthorInput'] | null> | null; // [CommentCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutAuthorInput'] | null> | null; // [CommentCreateWithoutAuthorInput]
    delete?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['CommentScalarWhereInput'] | null> | null; // [CommentScalarWhereInput]
    disconnect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    set?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    update?: Array<NexusGenInputs['CommentUpdateWithWhereUniqueWithoutAuthorInput'] | null> | null; // [CommentUpdateWithWhereUniqueWithoutAuthorInput]
    updateMany?: Array<NexusGenInputs['CommentUpdateManyWithWhereWithoutAuthorInput'] | null> | null; // [CommentUpdateManyWithWhereWithoutAuthorInput]
    upsert?: Array<NexusGenInputs['CommentUpsertWithWhereUniqueWithoutAuthorInput'] | null> | null; // [CommentUpsertWithWhereUniqueWithoutAuthorInput]
  }
  CommentUpdateManyWithoutPostInput: { // input type
    connect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['CommentCreateOrConnectWithoutpostInput'] | null> | null; // [CommentCreateOrConnectWithoutpostInput]
    create?: Array<NexusGenInputs['CommentCreateWithoutPostInput'] | null> | null; // [CommentCreateWithoutPostInput]
    delete?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['CommentScalarWhereInput'] | null> | null; // [CommentScalarWhereInput]
    disconnect?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    set?: Array<NexusGenInputs['CommentWhereUniqueInput'] | null> | null; // [CommentWhereUniqueInput]
    update?: Array<NexusGenInputs['CommentUpdateWithWhereUniqueWithoutPostInput'] | null> | null; // [CommentUpdateWithWhereUniqueWithoutPostInput]
    updateMany?: Array<NexusGenInputs['CommentUpdateManyWithWhereWithoutPostInput'] | null> | null; // [CommentUpdateManyWithWhereWithoutPostInput]
    upsert?: Array<NexusGenInputs['CommentUpsertWithWhereUniqueWithoutPostInput'] | null> | null; // [CommentUpsertWithWhereUniqueWithoutPostInput]
  }
  CommentUpdateWithWhereUniqueWithoutAuthorInput: { // input type
    data: NexusGenInputs['CommentUncheckedUpdateWithoutAuthorInput']; // CommentUncheckedUpdateWithoutAuthorInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpdateWithWhereUniqueWithoutPostInput: { // input type
    data: NexusGenInputs['CommentUncheckedUpdateWithoutPostInput']; // CommentUncheckedUpdateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpdateWithoutAuthorInput: { // input type
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    post?: NexusGenInputs['PostUpdateOneRequiredWithoutCommentsInput'] | null; // PostUpdateOneRequiredWithoutCommentsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUpdateWithoutPostInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutCommentsInput'] | null; // UserUpdateOneWithoutCommentsInput
    contain?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  CommentUpsertWithWhereUniqueWithoutAuthorInput: { // input type
    create: NexusGenInputs['CommentUncheckedCreateWithoutAuthorInput']; // CommentUncheckedCreateWithoutAuthorInput!
    update: NexusGenInputs['CommentUncheckedUpdateWithoutAuthorInput']; // CommentUncheckedUpdateWithoutAuthorInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpsertWithWhereUniqueWithoutPostInput: { // input type
    create: NexusGenInputs['CommentUncheckedCreateWithoutPostInput']; // CommentUncheckedCreateWithoutPostInput!
    update: NexusGenInputs['CommentUncheckedUpdateWithoutPostInput']; // CommentUncheckedUpdateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentWhereInput: { // input type
    AND?: Array<NexusGenInputs['CommentWhereInput'] | null> | null; // [CommentWhereInput]
    author?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    authorId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    contain?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: Array<NexusGenInputs['CommentWhereInput'] | null> | null; // [CommentWhereInput]
    OR?: Array<NexusGenInputs['CommentWhereInput'] | null> | null; // [CommentWhereInput]
    post?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    postId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  CommentWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  GroupCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    users?: NexusGenInputs['UserCreateManyWithoutGroupInput'] | null; // UserCreateManyWithoutGroupInput
  }
  GroupCreateOneWithoutUsersInput: { // input type
    connect?: NexusGenInputs['GroupWhereUniqueInput'] | null; // GroupWhereUniqueInput
    connectOrCreate?: NexusGenInputs['GroupCreateOrConnectWithoutusersInput'] | null; // GroupCreateOrConnectWithoutusersInput
    create?: NexusGenInputs['GroupUncheckedCreateWithoutUsersInput'] | null; // GroupUncheckedCreateWithoutUsersInput
  }
  GroupCreateOrConnectWithoutusersInput: { // input type
    create: NexusGenInputs['GroupUncheckedCreateWithoutUsersInput']; // GroupUncheckedCreateWithoutUsersInput!
    where: NexusGenInputs['GroupWhereUniqueInput']; // GroupWhereUniqueInput!
  }
  GroupCreateWithoutUsersInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GroupOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  GroupRelationFilter: { // input type
    is?: NexusGenInputs['GroupWhereInput'] | null; // GroupWhereInput
    isNot?: NexusGenInputs['GroupWhereInput'] | null; // GroupWhereInput
  }
  GroupUncheckedCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    users?: NexusGenInputs['UserUncheckedCreateManyWithoutGroupInput'] | null; // UserUncheckedCreateManyWithoutGroupInput
  }
  GroupUncheckedCreateWithoutUsersInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GroupUncheckedUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    users?: NexusGenInputs['UserUncheckedUpdateManyWithoutGroupInput'] | null; // UserUncheckedUpdateManyWithoutGroupInput
  }
  GroupUncheckedUpdateManyInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  GroupUncheckedUpdateWithoutUsersInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  GroupUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    users?: NexusGenInputs['UserUpdateManyWithoutGroupInput'] | null; // UserUpdateManyWithoutGroupInput
  }
  GroupUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  GroupUpdateOneWithoutUsersInput: { // input type
    connect?: NexusGenInputs['GroupWhereUniqueInput'] | null; // GroupWhereUniqueInput
    connectOrCreate?: NexusGenInputs['GroupCreateOrConnectWithoutusersInput'] | null; // GroupCreateOrConnectWithoutusersInput
    create?: NexusGenInputs['GroupUncheckedCreateWithoutUsersInput'] | null; // GroupUncheckedCreateWithoutUsersInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['GroupUncheckedUpdateWithoutUsersInput'] | null; // GroupUncheckedUpdateWithoutUsersInput
    upsert?: NexusGenInputs['GroupUpsertWithoutUsersInput'] | null; // GroupUpsertWithoutUsersInput
  }
  GroupUpdateWithoutUsersInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  GroupUpsertWithoutUsersInput: { // input type
    create: NexusGenInputs['GroupUncheckedCreateWithoutUsersInput']; // GroupUncheckedCreateWithoutUsersInput!
    update: NexusGenInputs['GroupUncheckedUpdateWithoutUsersInput']; // GroupUncheckedUpdateWithoutUsersInput!
  }
  GroupWhereInput: { // input type
    AND?: Array<NexusGenInputs['GroupWhereInput'] | null> | null; // [GroupWhereInput]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: Array<NexusGenInputs['GroupWhereInput'] | null> | null; // [GroupWhereInput]
    OR?: Array<NexusGenInputs['GroupWhereInput'] | null> | null; // [GroupWhereInput]
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    users?: NexusGenInputs['UserListRelationFilter'] | null; // UserListRelationFilter
  }
  GroupWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  IntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  NullableIntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  PostCreateInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    published?: boolean | null; // Boolean
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['PostCreateOrConnectWithoutauthorInput'] | null> | null; // [PostCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['PostCreateWithoutAuthorInput'] | null> | null; // [PostCreateWithoutAuthorInput]
  }
  PostCreateOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcommentsInput'] | null; // PostCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['PostUncheckedCreateWithoutCommentsInput'] | null; // PostUncheckedCreateWithoutCommentsInput
  }
  PostCreateOrConnectWithoutauthorInput: { // input type
    create: NexusGenInputs['PostUncheckedCreateWithoutAuthorInput']; // PostUncheckedCreateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutcommentsInput: { // input type
    create: NexusGenInputs['PostUncheckedCreateWithoutCommentsInput']; // PostUncheckedCreateWithoutCommentsInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateWithoutAuthorInput: { // input type
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    published?: boolean | null; // Boolean
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateWithoutCommentsInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    published?: boolean | null; // Boolean
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostListRelationFilter: { // input type
    every?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    none?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    some?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
  }
  PostOrderByInput: { // input type
    authorId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    published?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  PostRelationFilter: { // input type
    is?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    isNot?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
  }
  PostScalarWhereInput: { // input type
    AND?: Array<NexusGenInputs['PostScalarWhereInput'] | null> | null; // [PostScalarWhereInput]
    authorId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: Array<NexusGenInputs['PostScalarWhereInput'] | null> | null; // [PostScalarWhereInput]
    OR?: Array<NexusGenInputs['PostScalarWhereInput'] | null> | null; // [PostScalarWhereInput]
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  PostUncheckedCreateInput: { // input type
    authorId?: number | null; // Int
    comments?: NexusGenInputs['CommentUncheckedCreateManyWithoutPostInput'] | null; // CommentUncheckedCreateManyWithoutPostInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostUncheckedCreateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['PostCreateOrConnectWithoutauthorInput'] | null> | null; // [PostCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['PostCreateWithoutAuthorInput'] | null> | null; // [PostCreateWithoutAuthorInput]
  }
  PostUncheckedCreateWithoutAuthorInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedCreateManyWithoutPostInput'] | null; // CommentUncheckedCreateManyWithoutPostInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostUncheckedCreateWithoutCommentsInput: { // input type
    authorId?: number | null; // Int
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostUncheckedUpdateInput: { // input type
    authorId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    comments?: NexusGenInputs['CommentUncheckedUpdateManyWithoutPostInput'] | null; // CommentUncheckedUpdateManyWithoutPostInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUncheckedUpdateManyInput: { // input type
    authorId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUncheckedUpdateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['PostCreateOrConnectWithoutauthorInput'] | null> | null; // [PostCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['PostCreateWithoutAuthorInput'] | null> | null; // [PostCreateWithoutAuthorInput]
    delete?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['PostScalarWhereInput'] | null> | null; // [PostScalarWhereInput]
    disconnect?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    set?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    update?: Array<NexusGenInputs['PostUpdateWithWhereUniqueWithoutAuthorInput'] | null> | null; // [PostUpdateWithWhereUniqueWithoutAuthorInput]
    updateMany?: Array<NexusGenInputs['PostUpdateManyWithWhereWithoutAuthorInput'] | null> | null; // [PostUpdateManyWithWhereWithoutAuthorInput]
    upsert?: Array<NexusGenInputs['PostUpsertWithWhereUniqueWithoutAuthorInput'] | null> | null; // [PostUpsertWithWhereUniqueWithoutAuthorInput]
  }
  PostUncheckedUpdateManyWithoutPostsInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUncheckedUpdateWithoutAuthorInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedUpdateManyWithoutPostInput'] | null; // CommentUncheckedUpdateManyWithoutPostInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUncheckedUpdateWithoutCommentsInput: { // input type
    authorId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpdateInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpdateManyWithWhereWithoutAuthorInput: { // input type
    data: NexusGenInputs['PostUncheckedUpdateManyWithoutPostsInput']; // PostUncheckedUpdateManyWithoutPostsInput!
    where: NexusGenInputs['PostScalarWhereInput']; // PostScalarWhereInput!
  }
  PostUpdateManyWithoutAuthorInput: { // input type
    connect?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['PostCreateOrConnectWithoutauthorInput'] | null> | null; // [PostCreateOrConnectWithoutauthorInput]
    create?: Array<NexusGenInputs['PostCreateWithoutAuthorInput'] | null> | null; // [PostCreateWithoutAuthorInput]
    delete?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['PostScalarWhereInput'] | null> | null; // [PostScalarWhereInput]
    disconnect?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    set?: Array<NexusGenInputs['PostWhereUniqueInput'] | null> | null; // [PostWhereUniqueInput]
    update?: Array<NexusGenInputs['PostUpdateWithWhereUniqueWithoutAuthorInput'] | null> | null; // [PostUpdateWithWhereUniqueWithoutAuthorInput]
    updateMany?: Array<NexusGenInputs['PostUpdateManyWithWhereWithoutAuthorInput'] | null> | null; // [PostUpdateManyWithWhereWithoutAuthorInput]
    upsert?: Array<NexusGenInputs['PostUpsertWithWhereUniqueWithoutAuthorInput'] | null> | null; // [PostUpsertWithWhereUniqueWithoutAuthorInput]
  }
  PostUpdateOneRequiredWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcommentsInput'] | null; // PostCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['PostUncheckedCreateWithoutCommentsInput'] | null; // PostUncheckedCreateWithoutCommentsInput
    update?: NexusGenInputs['PostUncheckedUpdateWithoutCommentsInput'] | null; // PostUncheckedUpdateWithoutCommentsInput
    upsert?: NexusGenInputs['PostUpsertWithoutCommentsInput'] | null; // PostUpsertWithoutCommentsInput
  }
  PostUpdateWithWhereUniqueWithoutAuthorInput: { // input type
    data: NexusGenInputs['PostUncheckedUpdateWithoutAuthorInput']; // PostUncheckedUpdateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpdateWithoutAuthorInput: { // input type
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpdateWithoutCommentsInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpsertWithWhereUniqueWithoutAuthorInput: { // input type
    create: NexusGenInputs['PostUncheckedCreateWithoutAuthorInput']; // PostUncheckedCreateWithoutAuthorInput!
    update: NexusGenInputs['PostUncheckedUpdateWithoutAuthorInput']; // PostUncheckedUpdateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpsertWithoutCommentsInput: { // input type
    create: NexusGenInputs['PostUncheckedCreateWithoutCommentsInput']; // PostUncheckedCreateWithoutCommentsInput!
    update: NexusGenInputs['PostUncheckedUpdateWithoutCommentsInput']; // PostUncheckedUpdateWithoutCommentsInput!
  }
  PostWhereInput: { // input type
    AND?: Array<NexusGenInputs['PostWhereInput'] | null> | null; // [PostWhereInput]
    author?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    authorId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    comments?: NexusGenInputs['CommentListRelationFilter'] | null; // CommentListRelationFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: Array<NexusGenInputs['PostWhereInput'] | null> | null; // [PostWhereInput]
    OR?: Array<NexusGenInputs['PostWhereInput'] | null> | null; // [PostWhereInput]
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  PostWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  UpdateFieldInput: { // input type
    create?: boolean | null; // Boolean
    editor?: boolean | null; // Boolean
    filter?: boolean | null; // Boolean
    id?: string | null; // String
    isId?: boolean | null; // Boolean
    kind?: NexusGenEnums['KindEnum'] | null; // KindEnum
    list?: boolean | null; // Boolean
    name?: string | null; // String
    order?: number | null; // Int
    read?: boolean | null; // Boolean
    relationField?: boolean | null; // Boolean
    required?: boolean | null; // Boolean
    sort?: boolean | null; // Boolean
    title?: string | null; // String
    type?: string | null; // String
    unique?: boolean | null; // Boolean
    update?: boolean | null; // Boolean
    upload?: boolean | null; // Boolean
  }
  UpdateModelInput: { // input type
    create?: boolean | null; // Boolean
    delete?: boolean | null; // Boolean
    displayFields?: Array<string | null> | null; // [String]
    fields?: Array<NexusGenInputs['UpdateFieldInput'] | null> | null; // [UpdateFieldInput]
    idField?: string | null; // String
    name?: string | null; // String
    update?: boolean | null; // Boolean
  }
  UserCreateInput: { // input type
    comments?: NexusGenInputs['CommentCreateManyWithoutAuthorInput'] | null; // CommentCreateManyWithoutAuthorInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    group?: NexusGenInputs['GroupCreateOneWithoutUsersInput'] | null; // GroupCreateOneWithoutUsersInput
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutAuthorInput'] | null; // PostCreateManyWithoutAuthorInput
  }
  UserCreateManyWithoutGroupInput: { // input type
    connect?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['UserCreateOrConnectWithoutgroupInput'] | null> | null; // [UserCreateOrConnectWithoutgroupInput]
    create?: Array<NexusGenInputs['UserCreateWithoutGroupInput'] | null> | null; // [UserCreateWithoutGroupInput]
  }
  UserCreateOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutcommentsInput'] | null; // UserCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutCommentsInput'] | null; // UserUncheckedCreateWithoutCommentsInput
  }
  UserCreateOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutpostsInput'] | null; // UserCreateOrConnectWithoutpostsInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutPostsInput'] | null; // UserUncheckedCreateWithoutPostsInput
  }
  UserCreateOrConnectWithoutcommentsInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutCommentsInput']; // UserUncheckedCreateWithoutCommentsInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateOrConnectWithoutgroupInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutGroupInput']; // UserUncheckedCreateWithoutGroupInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateOrConnectWithoutpostsInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutPostsInput']; // UserUncheckedCreateWithoutPostsInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutCommentsInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    group?: NexusGenInputs['GroupCreateOneWithoutUsersInput'] | null; // GroupCreateOneWithoutUsersInput
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutAuthorInput'] | null; // PostCreateManyWithoutAuthorInput
  }
  UserCreateWithoutGroupInput: { // input type
    comments?: NexusGenInputs['CommentCreateManyWithoutAuthorInput'] | null; // CommentCreateManyWithoutAuthorInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutAuthorInput'] | null; // PostCreateManyWithoutAuthorInput
  }
  UserCreateWithoutPostsInput: { // input type
    comments?: NexusGenInputs['CommentCreateManyWithoutAuthorInput'] | null; // CommentCreateManyWithoutAuthorInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    group?: NexusGenInputs['GroupCreateOneWithoutUsersInput'] | null; // GroupCreateOneWithoutUsersInput
    name?: string | null; // String
    password: string; // String!
  }
  UserListRelationFilter: { // input type
    every?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    none?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    some?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
  }
  UserOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    groupId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    password?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserRelationFilter: { // input type
    is?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    isNot?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
  }
  UserScalarWhereInput: { // input type
    AND?: Array<NexusGenInputs['UserScalarWhereInput'] | null> | null; // [UserScalarWhereInput]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    groupId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: Array<NexusGenInputs['UserScalarWhereInput'] | null> | null; // [UserScalarWhereInput]
    OR?: Array<NexusGenInputs['UserScalarWhereInput'] | null> | null; // [UserScalarWhereInput]
    password?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  UserUncheckedCreateInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedCreateManyWithoutAuthorInput'] | null; // CommentUncheckedCreateManyWithoutAuthorInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    groupId?: number | null; // Int
    id?: number | null; // Int
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostUncheckedCreateManyWithoutAuthorInput'] | null; // PostUncheckedCreateManyWithoutAuthorInput
  }
  UserUncheckedCreateManyWithoutGroupInput: { // input type
    connect?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['UserCreateOrConnectWithoutgroupInput'] | null> | null; // [UserCreateOrConnectWithoutgroupInput]
    create?: Array<NexusGenInputs['UserCreateWithoutGroupInput'] | null> | null; // [UserCreateWithoutGroupInput]
  }
  UserUncheckedCreateWithoutCommentsInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    groupId?: number | null; // Int
    id?: number | null; // Int
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostUncheckedCreateManyWithoutAuthorInput'] | null; // PostUncheckedCreateManyWithoutAuthorInput
  }
  UserUncheckedCreateWithoutGroupInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedCreateManyWithoutAuthorInput'] | null; // CommentUncheckedCreateManyWithoutAuthorInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    id?: number | null; // Int
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostUncheckedCreateManyWithoutAuthorInput'] | null; // PostUncheckedCreateManyWithoutAuthorInput
  }
  UserUncheckedCreateWithoutPostsInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedCreateManyWithoutAuthorInput'] | null; // CommentUncheckedCreateManyWithoutAuthorInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    groupId?: number | null; // Int
    id?: number | null; // Int
    name?: string | null; // String
    password: string; // String!
  }
  UserUncheckedUpdateInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedUpdateManyWithoutAuthorInput'] | null; // CommentUncheckedUpdateManyWithoutAuthorInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    groupId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUncheckedUpdateManyWithoutAuthorInput'] | null; // PostUncheckedUpdateManyWithoutAuthorInput
  }
  UserUncheckedUpdateManyInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    groupId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserUncheckedUpdateManyWithoutGroupInput: { // input type
    connect?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['UserCreateOrConnectWithoutgroupInput'] | null> | null; // [UserCreateOrConnectWithoutgroupInput]
    create?: Array<NexusGenInputs['UserCreateWithoutGroupInput'] | null> | null; // [UserCreateWithoutGroupInput]
    delete?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['UserScalarWhereInput'] | null> | null; // [UserScalarWhereInput]
    disconnect?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    set?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    update?: Array<NexusGenInputs['UserUpdateWithWhereUniqueWithoutGroupInput'] | null> | null; // [UserUpdateWithWhereUniqueWithoutGroupInput]
    updateMany?: Array<NexusGenInputs['UserUpdateManyWithWhereWithoutGroupInput'] | null> | null; // [UserUpdateManyWithWhereWithoutGroupInput]
    upsert?: Array<NexusGenInputs['UserUpsertWithWhereUniqueWithoutGroupInput'] | null> | null; // [UserUpsertWithWhereUniqueWithoutGroupInput]
  }
  UserUncheckedUpdateManyWithoutUsersInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserUncheckedUpdateWithoutCommentsInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    groupId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUncheckedUpdateManyWithoutAuthorInput'] | null; // PostUncheckedUpdateManyWithoutAuthorInput
  }
  UserUncheckedUpdateWithoutGroupInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedUpdateManyWithoutAuthorInput'] | null; // CommentUncheckedUpdateManyWithoutAuthorInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUncheckedUpdateManyWithoutAuthorInput'] | null; // PostUncheckedUpdateManyWithoutAuthorInput
  }
  UserUncheckedUpdateWithoutPostsInput: { // input type
    comments?: NexusGenInputs['CommentUncheckedUpdateManyWithoutAuthorInput'] | null; // CommentUncheckedUpdateManyWithoutAuthorInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    groupId?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    id?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserUpdateInput: { // input type
    comments?: NexusGenInputs['CommentUpdateManyWithoutAuthorInput'] | null; // CommentUpdateManyWithoutAuthorInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    group?: NexusGenInputs['GroupUpdateOneWithoutUsersInput'] | null; // GroupUpdateOneWithoutUsersInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutAuthorInput'] | null; // PostUpdateManyWithoutAuthorInput
  }
  UserUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserUpdateManyWithWhereWithoutGroupInput: { // input type
    data: NexusGenInputs['UserUncheckedUpdateManyWithoutUsersInput']; // UserUncheckedUpdateManyWithoutUsersInput!
    where: NexusGenInputs['UserScalarWhereInput']; // UserScalarWhereInput!
  }
  UserUpdateManyWithoutGroupInput: { // input type
    connect?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['UserCreateOrConnectWithoutgroupInput'] | null> | null; // [UserCreateOrConnectWithoutgroupInput]
    create?: Array<NexusGenInputs['UserCreateWithoutGroupInput'] | null> | null; // [UserCreateWithoutGroupInput]
    delete?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['UserScalarWhereInput'] | null> | null; // [UserScalarWhereInput]
    disconnect?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    set?: Array<NexusGenInputs['UserWhereUniqueInput'] | null> | null; // [UserWhereUniqueInput]
    update?: Array<NexusGenInputs['UserUpdateWithWhereUniqueWithoutGroupInput'] | null> | null; // [UserUpdateWithWhereUniqueWithoutGroupInput]
    updateMany?: Array<NexusGenInputs['UserUpdateManyWithWhereWithoutGroupInput'] | null> | null; // [UserUpdateManyWithWhereWithoutGroupInput]
    upsert?: Array<NexusGenInputs['UserUpsertWithWhereUniqueWithoutGroupInput'] | null> | null; // [UserUpsertWithWhereUniqueWithoutGroupInput]
  }
  UserUpdateOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutcommentsInput'] | null; // UserCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutCommentsInput'] | null; // UserUncheckedCreateWithoutCommentsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['UserUncheckedUpdateWithoutCommentsInput'] | null; // UserUncheckedUpdateWithoutCommentsInput
    upsert?: NexusGenInputs['UserUpsertWithoutCommentsInput'] | null; // UserUpsertWithoutCommentsInput
  }
  UserUpdateOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutpostsInput'] | null; // UserCreateOrConnectWithoutpostsInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutPostsInput'] | null; // UserUncheckedCreateWithoutPostsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['UserUncheckedUpdateWithoutPostsInput'] | null; // UserUncheckedUpdateWithoutPostsInput
    upsert?: NexusGenInputs['UserUpsertWithoutPostsInput'] | null; // UserUpsertWithoutPostsInput
  }
  UserUpdateWithWhereUniqueWithoutGroupInput: { // input type
    data: NexusGenInputs['UserUncheckedUpdateWithoutGroupInput']; // UserUncheckedUpdateWithoutGroupInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserUpdateWithoutCommentsInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    group?: NexusGenInputs['GroupUpdateOneWithoutUsersInput'] | null; // GroupUpdateOneWithoutUsersInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutAuthorInput'] | null; // PostUpdateManyWithoutAuthorInput
  }
  UserUpdateWithoutGroupInput: { // input type
    comments?: NexusGenInputs['CommentUpdateManyWithoutAuthorInput'] | null; // CommentUpdateManyWithoutAuthorInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutAuthorInput'] | null; // PostUpdateManyWithoutAuthorInput
  }
  UserUpdateWithoutPostsInput: { // input type
    comments?: NexusGenInputs['CommentUpdateManyWithoutAuthorInput'] | null; // CommentUpdateManyWithoutAuthorInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    group?: NexusGenInputs['GroupUpdateOneWithoutUsersInput'] | null; // GroupUpdateOneWithoutUsersInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    password?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserUpsertWithWhereUniqueWithoutGroupInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutGroupInput']; // UserUncheckedCreateWithoutGroupInput!
    update: NexusGenInputs['UserUncheckedUpdateWithoutGroupInput']; // UserUncheckedUpdateWithoutGroupInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserUpsertWithoutCommentsInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutCommentsInput']; // UserUncheckedCreateWithoutCommentsInput!
    update: NexusGenInputs['UserUncheckedUpdateWithoutCommentsInput']; // UserUncheckedUpdateWithoutCommentsInput!
  }
  UserUpsertWithoutPostsInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutPostsInput']; // UserUncheckedCreateWithoutPostsInput!
    update: NexusGenInputs['UserUncheckedUpdateWithoutPostsInput']; // UserUncheckedUpdateWithoutPostsInput!
  }
  UserWhereInput: { // input type
    AND?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    comments?: NexusGenInputs['CommentListRelationFilter'] | null; // CommentListRelationFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    group?: NexusGenInputs['GroupWhereInput'] | null; // GroupWhereInput
    groupId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    OR?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    password?: NexusGenInputs['StringFilter'] | null; // StringFilter
    posts?: NexusGenInputs['PostListRelationFilter'] | null; // PostListRelationFilter
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  CommentScalarFieldEnum: "authorId" | "contain" | "createdAt" | "id" | "postId" | "updatedAt"
  GroupScalarFieldEnum: "createdAt" | "id" | "name" | "updatedAt"
  KindEnum: "enum" | "object" | "scalar"
  PostScalarFieldEnum: "authorId" | "createdAt" | "id" | "published" | "title" | "updatedAt"
  SortOrder: "asc" | "desc"
  UserScalarFieldEnum: "createdAt" | "email" | "groupId" | "id" | "name" | "password"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  Json: any
}

export interface NexusGenObjects {
  AggregateComment: { // root type
    avg?: NexusGenRootTypes['CommentAvgAggregateOutputType'] | null; // CommentAvgAggregateOutputType
    count?: NexusGenRootTypes['CommentCountAggregateOutputType'] | null; // CommentCountAggregateOutputType
    max?: NexusGenRootTypes['CommentMaxAggregateOutputType'] | null; // CommentMaxAggregateOutputType
    min?: NexusGenRootTypes['CommentMinAggregateOutputType'] | null; // CommentMinAggregateOutputType
    sum?: NexusGenRootTypes['CommentSumAggregateOutputType'] | null; // CommentSumAggregateOutputType
  }
  AggregateGroup: { // root type
    avg?: NexusGenRootTypes['GroupAvgAggregateOutputType'] | null; // GroupAvgAggregateOutputType
    count?: NexusGenRootTypes['GroupCountAggregateOutputType'] | null; // GroupCountAggregateOutputType
    max?: NexusGenRootTypes['GroupMaxAggregateOutputType'] | null; // GroupMaxAggregateOutputType
    min?: NexusGenRootTypes['GroupMinAggregateOutputType'] | null; // GroupMinAggregateOutputType
    sum?: NexusGenRootTypes['GroupSumAggregateOutputType'] | null; // GroupSumAggregateOutputType
  }
  AggregatePost: { // root type
    avg?: NexusGenRootTypes['PostAvgAggregateOutputType'] | null; // PostAvgAggregateOutputType
    count?: NexusGenRootTypes['PostCountAggregateOutputType'] | null; // PostCountAggregateOutputType
    max?: NexusGenRootTypes['PostMaxAggregateOutputType'] | null; // PostMaxAggregateOutputType
    min?: NexusGenRootTypes['PostMinAggregateOutputType'] | null; // PostMinAggregateOutputType
    sum?: NexusGenRootTypes['PostSumAggregateOutputType'] | null; // PostSumAggregateOutputType
  }
  AggregateUser: { // root type
    avg?: NexusGenRootTypes['UserAvgAggregateOutputType'] | null; // UserAvgAggregateOutputType
    count?: NexusGenRootTypes['UserCountAggregateOutputType'] | null; // UserCountAggregateOutputType
    max?: NexusGenRootTypes['UserMaxAggregateOutputType'] | null; // UserMaxAggregateOutputType
    min?: NexusGenRootTypes['UserMinAggregateOutputType'] | null; // UserMinAggregateOutputType
    sum?: NexusGenRootTypes['UserSumAggregateOutputType'] | null; // UserSumAggregateOutputType
  }
  BatchPayload: { // root type
    count: number; // Int!
  }
  Brand: { // root type
    id?: number | null; // Int
    name?: string | null; // String
  }
  CommentAvgAggregateOutputType: { // root type
    authorId?: number | null; // Float
    id?: number | null; // Float
    postId?: number | null; // Float
  }
  CommentCountAggregateOutputType: { // root type
    _all?: number | null; // Int
    authorId?: number | null; // Int
    contain?: number | null; // Int
    createdAt?: number | null; // Int
    id?: number | null; // Int
    postId?: number | null; // Int
    updatedAt?: number | null; // Int
  }
  CommentMaxAggregateOutputType: { // root type
    authorId?: number | null; // Int
    contain?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    postId?: number | null; // Int
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentMinAggregateOutputType: { // root type
    authorId?: number | null; // Int
    contain?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    postId?: number | null; // Int
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentSumAggregateOutputType: { // root type
    authorId?: number | null; // Int
    id?: number | null; // Int
    postId?: number | null; // Int
  }
  Enum: { // root type
    fields: string[]; // [String!]!
    name: string; // String!
  }
  Field: { // root type
    create: boolean; // Boolean!
    editor: boolean; // Boolean!
    filter: boolean; // Boolean!
    id: string; // String!
    isId: boolean; // Boolean!
    kind: NexusGenEnums['KindEnum']; // KindEnum!
    list: boolean; // Boolean!
    name: string; // String!
    order: number; // Int!
    read: boolean; // Boolean!
    relationField?: boolean | null; // Boolean
    required: boolean; // Boolean!
    sort: boolean; // Boolean!
    title: string; // String!
    type: string; // String!
    unique: boolean; // Boolean!
    update: boolean; // Boolean!
    upload: boolean; // Boolean!
  }
  GroupAvgAggregateOutputType: { // root type
    id?: number | null; // Float
  }
  GroupCountAggregateOutputType: { // root type
    _all?: number | null; // Int
    createdAt?: number | null; // Int
    id?: number | null; // Int
    name?: number | null; // Int
    updatedAt?: number | null; // Int
  }
  GroupMaxAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GroupMinAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GroupSumAggregateOutputType: { // root type
    id?: number | null; // Int
  }
  Model: { // root type
    create: boolean; // Boolean!
    delete: boolean; // Boolean!
    displayFields: string[]; // [String!]!
    fields: NexusGenRootTypes['Field'][]; // [Field!]!
    id: string; // String!
    idField: string; // String!
    name: string; // String!
    update: boolean; // Boolean!
  }
  Mutation: {};
  PostAvgAggregateOutputType: { // root type
    authorId?: number | null; // Float
    id?: number | null; // Float
  }
  PostCountAggregateOutputType: { // root type
    _all?: number | null; // Int
    authorId?: number | null; // Int
    createdAt?: number | null; // Int
    id?: number | null; // Int
    published?: number | null; // Int
    title?: number | null; // Int
    updatedAt?: number | null; // Int
  }
  PostMaxAggregateOutputType: { // root type
    authorId?: number | null; // Int
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostMinAggregateOutputType: { // root type
    authorId?: number | null; // Int
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostSumAggregateOutputType: { // root type
    authorId?: number | null; // Int
    id?: number | null; // Int
  }
  Product: { // root type
    brand?: NexusGenRootTypes['Brand'] | null; // Brand
    id?: number | null; // Int
    name?: string | null; // String
  }
  Query: {};
  Schema: { // root type
    enums: NexusGenRootTypes['Enum'][]; // [Enum!]!
    models: NexusGenRootTypes['Model'][]; // [Model!]!
  }
  UserAvgAggregateOutputType: { // root type
    groupId?: number | null; // Float
    id?: number | null; // Float
  }
  UserCountAggregateOutputType: { // root type
    _all?: number | null; // Int
    createdAt?: number | null; // Int
    email?: number | null; // Int
    groupId?: number | null; // Int
    id?: number | null; // Int
    name?: number | null; // Int
    password?: number | null; // Int
  }
  UserMaxAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    groupId?: number | null; // Int
    id?: number | null; // Int
    name?: string | null; // String
    password?: string | null; // String
  }
  UserMinAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    groupId?: number | null; // Int
    id?: number | null; // Int
    name?: string | null; // String
    password?: string | null; // String
  }
  UserSumAggregateOutputType: { // root type
    groupId?: number | null; // Int
    id?: number | null; // Int
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AggregateComment: { // field return type
    avg: NexusGenRootTypes['CommentAvgAggregateOutputType'] | null; // CommentAvgAggregateOutputType
    count: NexusGenRootTypes['CommentCountAggregateOutputType'] | null; // CommentCountAggregateOutputType
    max: NexusGenRootTypes['CommentMaxAggregateOutputType'] | null; // CommentMaxAggregateOutputType
    min: NexusGenRootTypes['CommentMinAggregateOutputType'] | null; // CommentMinAggregateOutputType
    sum: NexusGenRootTypes['CommentSumAggregateOutputType'] | null; // CommentSumAggregateOutputType
  }
  AggregateGroup: { // field return type
    avg: NexusGenRootTypes['GroupAvgAggregateOutputType'] | null; // GroupAvgAggregateOutputType
    count: NexusGenRootTypes['GroupCountAggregateOutputType'] | null; // GroupCountAggregateOutputType
    max: NexusGenRootTypes['GroupMaxAggregateOutputType'] | null; // GroupMaxAggregateOutputType
    min: NexusGenRootTypes['GroupMinAggregateOutputType'] | null; // GroupMinAggregateOutputType
    sum: NexusGenRootTypes['GroupSumAggregateOutputType'] | null; // GroupSumAggregateOutputType
  }
  AggregatePost: { // field return type
    avg: NexusGenRootTypes['PostAvgAggregateOutputType'] | null; // PostAvgAggregateOutputType
    count: NexusGenRootTypes['PostCountAggregateOutputType'] | null; // PostCountAggregateOutputType
    max: NexusGenRootTypes['PostMaxAggregateOutputType'] | null; // PostMaxAggregateOutputType
    min: NexusGenRootTypes['PostMinAggregateOutputType'] | null; // PostMinAggregateOutputType
    sum: NexusGenRootTypes['PostSumAggregateOutputType'] | null; // PostSumAggregateOutputType
  }
  AggregateUser: { // field return type
    avg: NexusGenRootTypes['UserAvgAggregateOutputType'] | null; // UserAvgAggregateOutputType
    count: NexusGenRootTypes['UserCountAggregateOutputType'] | null; // UserCountAggregateOutputType
    max: NexusGenRootTypes['UserMaxAggregateOutputType'] | null; // UserMaxAggregateOutputType
    min: NexusGenRootTypes['UserMinAggregateOutputType'] | null; // UserMinAggregateOutputType
    sum: NexusGenRootTypes['UserSumAggregateOutputType'] | null; // UserSumAggregateOutputType
  }
  BatchPayload: { // field return type
    count: number; // Int!
  }
  Brand: { // field return type
    id: number | null; // Int
    name: string | null; // String
  }
  CommentAvgAggregateOutputType: { // field return type
    authorId: number | null; // Float
    id: number | null; // Float
    postId: number | null; // Float
  }
  CommentCountAggregateOutputType: { // field return type
    _all: number | null; // Int
    authorId: number | null; // Int
    contain: number | null; // Int
    createdAt: number | null; // Int
    id: number | null; // Int
    postId: number | null; // Int
    updatedAt: number | null; // Int
  }
  CommentMaxAggregateOutputType: { // field return type
    authorId: number | null; // Int
    contain: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    postId: number | null; // Int
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentMinAggregateOutputType: { // field return type
    authorId: number | null; // Int
    contain: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    postId: number | null; // Int
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentSumAggregateOutputType: { // field return type
    authorId: number | null; // Int
    id: number | null; // Int
    postId: number | null; // Int
  }
  Enum: { // field return type
    fields: string[]; // [String!]!
    name: string; // String!
  }
  Field: { // field return type
    create: boolean; // Boolean!
    editor: boolean; // Boolean!
    filter: boolean; // Boolean!
    id: string; // String!
    isId: boolean; // Boolean!
    kind: NexusGenEnums['KindEnum']; // KindEnum!
    list: boolean; // Boolean!
    name: string; // String!
    order: number; // Int!
    read: boolean; // Boolean!
    relationField: boolean | null; // Boolean
    required: boolean; // Boolean!
    sort: boolean; // Boolean!
    title: string; // String!
    type: string; // String!
    unique: boolean; // Boolean!
    update: boolean; // Boolean!
    upload: boolean; // Boolean!
  }
  GroupAvgAggregateOutputType: { // field return type
    id: number | null; // Float
  }
  GroupCountAggregateOutputType: { // field return type
    _all: number | null; // Int
    createdAt: number | null; // Int
    id: number | null; // Int
    name: number | null; // Int
    updatedAt: number | null; // Int
  }
  GroupMaxAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GroupMinAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GroupSumAggregateOutputType: { // field return type
    id: number | null; // Int
  }
  Model: { // field return type
    create: boolean; // Boolean!
    delete: boolean; // Boolean!
    displayFields: string[]; // [String!]!
    fields: NexusGenRootTypes['Field'][]; // [Field!]!
    id: string; // String!
    idField: string; // String!
    name: string; // String!
    update: boolean; // Boolean!
  }
  Mutation: { // field return type
    updateField: NexusGenRootTypes['Field']; // Field!
    updateModel: NexusGenRootTypes['Model']; // Model!
  }
  PostAvgAggregateOutputType: { // field return type
    authorId: number | null; // Float
    id: number | null; // Float
  }
  PostCountAggregateOutputType: { // field return type
    _all: number | null; // Int
    authorId: number | null; // Int
    createdAt: number | null; // Int
    id: number | null; // Int
    published: number | null; // Int
    title: number | null; // Int
    updatedAt: number | null; // Int
  }
  PostMaxAggregateOutputType: { // field return type
    authorId: number | null; // Int
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    published: boolean | null; // Boolean
    title: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostMinAggregateOutputType: { // field return type
    authorId: number | null; // Int
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number | null; // Int
    published: boolean | null; // Boolean
    title: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostSumAggregateOutputType: { // field return type
    authorId: number | null; // Int
    id: number | null; // Int
  }
  Product: { // field return type
    brand: NexusGenRootTypes['Brand'] | null; // Brand
    id: number | null; // Int
    name: string | null; // String
  }
  Query: { // field return type
    brands: Array<NexusGenRootTypes['Brand'] | null> | null; // [Brand]
    getSchema: NexusGenRootTypes['Schema']; // Schema!
    products: Array<NexusGenRootTypes['Product'] | null> | null; // [Product]
  }
  Schema: { // field return type
    enums: NexusGenRootTypes['Enum'][]; // [Enum!]!
    models: NexusGenRootTypes['Model'][]; // [Model!]!
  }
  UserAvgAggregateOutputType: { // field return type
    groupId: number | null; // Float
    id: number | null; // Float
  }
  UserCountAggregateOutputType: { // field return type
    _all: number | null; // Int
    createdAt: number | null; // Int
    email: number | null; // Int
    groupId: number | null; // Int
    id: number | null; // Int
    name: number | null; // Int
    password: number | null; // Int
  }
  UserMaxAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    groupId: number | null; // Int
    id: number | null; // Int
    name: string | null; // String
    password: string | null; // String
  }
  UserMinAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    groupId: number | null; // Int
    id: number | null; // Int
    name: string | null; // String
    password: string | null; // String
  }
  UserSumAggregateOutputType: { // field return type
    groupId: number | null; // Int
    id: number | null; // Int
  }
}

export interface NexusGenFieldTypeNames {
  AggregateComment: { // field return type name
    avg: 'CommentAvgAggregateOutputType'
    count: 'CommentCountAggregateOutputType'
    max: 'CommentMaxAggregateOutputType'
    min: 'CommentMinAggregateOutputType'
    sum: 'CommentSumAggregateOutputType'
  }
  AggregateGroup: { // field return type name
    avg: 'GroupAvgAggregateOutputType'
    count: 'GroupCountAggregateOutputType'
    max: 'GroupMaxAggregateOutputType'
    min: 'GroupMinAggregateOutputType'
    sum: 'GroupSumAggregateOutputType'
  }
  AggregatePost: { // field return type name
    avg: 'PostAvgAggregateOutputType'
    count: 'PostCountAggregateOutputType'
    max: 'PostMaxAggregateOutputType'
    min: 'PostMinAggregateOutputType'
    sum: 'PostSumAggregateOutputType'
  }
  AggregateUser: { // field return type name
    avg: 'UserAvgAggregateOutputType'
    count: 'UserCountAggregateOutputType'
    max: 'UserMaxAggregateOutputType'
    min: 'UserMinAggregateOutputType'
    sum: 'UserSumAggregateOutputType'
  }
  BatchPayload: { // field return type name
    count: 'Int'
  }
  Brand: { // field return type name
    id: 'Int'
    name: 'String'
  }
  CommentAvgAggregateOutputType: { // field return type name
    authorId: 'Float'
    id: 'Float'
    postId: 'Float'
  }
  CommentCountAggregateOutputType: { // field return type name
    _all: 'Int'
    authorId: 'Int'
    contain: 'Int'
    createdAt: 'Int'
    id: 'Int'
    postId: 'Int'
    updatedAt: 'Int'
  }
  CommentMaxAggregateOutputType: { // field return type name
    authorId: 'Int'
    contain: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    postId: 'Int'
    updatedAt: 'DateTime'
  }
  CommentMinAggregateOutputType: { // field return type name
    authorId: 'Int'
    contain: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    postId: 'Int'
    updatedAt: 'DateTime'
  }
  CommentSumAggregateOutputType: { // field return type name
    authorId: 'Int'
    id: 'Int'
    postId: 'Int'
  }
  Enum: { // field return type name
    fields: 'String'
    name: 'String'
  }
  Field: { // field return type name
    create: 'Boolean'
    editor: 'Boolean'
    filter: 'Boolean'
    id: 'String'
    isId: 'Boolean'
    kind: 'KindEnum'
    list: 'Boolean'
    name: 'String'
    order: 'Int'
    read: 'Boolean'
    relationField: 'Boolean'
    required: 'Boolean'
    sort: 'Boolean'
    title: 'String'
    type: 'String'
    unique: 'Boolean'
    update: 'Boolean'
    upload: 'Boolean'
  }
  GroupAvgAggregateOutputType: { // field return type name
    id: 'Float'
  }
  GroupCountAggregateOutputType: { // field return type name
    _all: 'Int'
    createdAt: 'Int'
    id: 'Int'
    name: 'Int'
    updatedAt: 'Int'
  }
  GroupMaxAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    id: 'Int'
    name: 'String'
    updatedAt: 'DateTime'
  }
  GroupMinAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    id: 'Int'
    name: 'String'
    updatedAt: 'DateTime'
  }
  GroupSumAggregateOutputType: { // field return type name
    id: 'Int'
  }
  Model: { // field return type name
    create: 'Boolean'
    delete: 'Boolean'
    displayFields: 'String'
    fields: 'Field'
    id: 'String'
    idField: 'String'
    name: 'String'
    update: 'Boolean'
  }
  Mutation: { // field return type name
    updateField: 'Field'
    updateModel: 'Model'
  }
  PostAvgAggregateOutputType: { // field return type name
    authorId: 'Float'
    id: 'Float'
  }
  PostCountAggregateOutputType: { // field return type name
    _all: 'Int'
    authorId: 'Int'
    createdAt: 'Int'
    id: 'Int'
    published: 'Int'
    title: 'Int'
    updatedAt: 'Int'
  }
  PostMaxAggregateOutputType: { // field return type name
    authorId: 'Int'
    createdAt: 'DateTime'
    id: 'Int'
    published: 'Boolean'
    title: 'String'
    updatedAt: 'DateTime'
  }
  PostMinAggregateOutputType: { // field return type name
    authorId: 'Int'
    createdAt: 'DateTime'
    id: 'Int'
    published: 'Boolean'
    title: 'String'
    updatedAt: 'DateTime'
  }
  PostSumAggregateOutputType: { // field return type name
    authorId: 'Int'
    id: 'Int'
  }
  Product: { // field return type name
    brand: 'Brand'
    id: 'Int'
    name: 'String'
  }
  Query: { // field return type name
    brands: 'Brand'
    getSchema: 'Schema'
    products: 'Product'
  }
  Schema: { // field return type name
    enums: 'Enum'
    models: 'Model'
  }
  UserAvgAggregateOutputType: { // field return type name
    groupId: 'Float'
    id: 'Float'
  }
  UserCountAggregateOutputType: { // field return type name
    _all: 'Int'
    createdAt: 'Int'
    email: 'Int'
    groupId: 'Int'
    id: 'Int'
    name: 'Int'
    password: 'Int'
  }
  UserMaxAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    groupId: 'Int'
    id: 'Int'
    name: 'String'
    password: 'String'
  }
  UserMinAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    groupId: 'Int'
    id: 'Int'
    name: 'String'
    password: 'String'
  }
  UserSumAggregateOutputType: { // field return type name
    groupId: 'Int'
    id: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    updateField: { // args
      data: NexusGenInputs['UpdateFieldInput']; // UpdateFieldInput!
      id: string; // String!
      modelId: string; // String!
    }
    updateModel: { // args
      data: NexusGenInputs['UpdateModelInput']; // UpdateModelInput!
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}